apiVersion: v1
kind: Service
metadata:
  # This name for the service will be utilized inside of
  # our deployment
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  # The external port 80 will be mapped to internal port 80
  # 80 is the default port where nginx web server is run.
  - port: 80

# The service above is ClusterIP. Only available from the Kubernetes
# cluster
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        # Official Docker image nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80

